### PR TITLE
Page Layout

### PR DESCRIPTION
**Pull request by EidHachem**
This PR  adds a heading and design to the website to make it more appealing.

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @EidHachem, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 👏 

## Required
- [x] Make sure to add readme from this [template](https://github.com/microverseinc/readme-template).
- [x] Add node_modules to .gitignore as per requirements.
- [ ] Add descriptive Pul Request title and summary.

## Highlights
- All linter passing 👍
- Good commit messages 👍 

**Optional: Be sure to capitalize commit messages from the next project.**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by EidHachem** [comment]
Hello @sja-thedude 

I updated the readme.md and .gitignore files but couldn't figure out how to edit pull request title and summary, can you please help me with it?

Thank you in advance.

**Comment by sja-thedude** [comment]
@EidHachem Just make sure to replace the content with a good title for the project and where it is mentioned no description! Kindly add a description about the project!

 image

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @EidHachem ,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

# Required Changes ♻️

- [ ] Currently, your linter in this project is not working properly. Please fix it.

- [ ] Check the comments under the review for more suggestions. :arrow_down: 

###  To Highlights
:heavy_check_mark: Clean code
:heavy_check_mark: Github flow used properly.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by EidHachem** [comment]
Hi @mahbubul14 
Thank you for the review, I did the requested changes in the README.md file, but linters still not working, can you please advise what could be the problem? it was working the first time and I haven't changed anything in the linters.yml file, I just added node_modules to .gitignore 
I noticed that in the in the provided steps they mentioned that it would start on the first pull request, doesn't it mean that I have to issue a new PR?

Thanks for your assistance.

**Comment by mahbubul14** [comment]
Hi @EidHachem,
I think you have no issue with linter now. It is working properly.

**Comment by EidHachem** [comment]
@mahbubul14 Thank you for the assistance, I will submit it for the last review hopefully it will be accepted this time.
Thanks for being so helpful guys @sja-thedude @mahbubul14 .

**Review by sja-thedude — APPROVED** [review]
Hi @EidHachem, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

**Note: Don't worry about linters. There are some issues going on with GitHub actions and its taking long for linters to work.**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
